version: '3'

services:
  gympass-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockergympass
      - POSTGRES_DATABASE=gympassapi
