name: Run E2E Tests

# Each time an user make a pull request
on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    # Run all tests on a ubuntu machine, with the latest version
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DATABASE: gympass

    steps:
      # Download the code to our device
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # Github creates cache from dependencies and only download newest
          cache: "npm"

      # It avoids question the user, or modify our application (only install libs)
      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gympass?schema=public"
